### ISSUE TITLE
On make ".../bin/phyml-master/src/stats.c:4704: undefined reference to `MIGREP_Is_In_Polygon'"

### ISSUE THREAD

**Issue by thirtysix** [stephaneguindon/phyml#4]
In stats.c at line 4704 there is an undefined reference to function 'MIGREP_Is_In_Polygon', which is defined in migrep.c.

**Comment by stephaneguindon** [comment]
That'right. I've fixed that issue. Thank you.

**Comment by thirtysix** [comment]
I am still seeing it after running the most recent version, has the change been pushed?

**Comment by thirtysix** [comment]
My apologies, I was running out of the directory for the previous version.  This error is not present in your most recent version.
